channel_length: 12
channel_width: 0.3
bottom_types:
  - NOISE
  - SLOPE
  - BARS
parameter_names:
  - H0
  - Q0
  - SLOPE
  - n
  - nut
  - Ar
  - Vr
  - Hr
  - Fr
  - Re
  - M
variable_names:
  - H
  - U
  - V
  #- B
