name: ML
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - abseil-cpp=20230802.0
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.1.0
  - autopep8=2.0.4
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - black=24.4.2
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.2
  - cachetools=5.3.3
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cryptography=41.0.3
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - filelock=3.13.1
  - flatbuffers=2.0.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.3.1
  - gast=0.4.0
  - giflib=5.2.1
  - gmpy2=2.1.2
  - google-auth=2.29.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpc-cpp=1.48.2
  - grpcio=1.42.0
  - gtest=1.14.0
  - h5py=3.11.0
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.25.0
  - isort=5.13.2
  - jedi=0.18.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_code_formatter=2.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupytext=1.16.1
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.7.1
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - loguru=0.5.3
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - mypy_extensions=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.10.3
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=3.10.0
  - plotly=5.22.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=3.20.3
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=5
  - pycodestyle=2.11.1
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=2.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytorch=2.3.0
  - pytz=2024.1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - re2=2022.04.01
  - referencing=0.30.2
  - requests=2.32.2
  - requests-oauthlib=1.3.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - rsa=4.7.2
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=69.5.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - tenacity=8.2.2
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.1.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.3
  - wheel=0.43.0
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.14.1
  - xarray=2023.6.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cftime==1.6.4
      - configmypy==0.2.0
      - docker-pycreds==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - iniconfig==2.0.0
      - netcdf4==1.7.0
      - neuraloperator==0.3.0
      - pluggy==1.5.0
      - pytest==8.2.2
      - pytest-mock==3.14.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - sentry-sdk==2.9.0
      - setproctitle==1.3.3
      - shapely==2.0.4
      - smmap==5.0.1
      - tensorly==0.8.1
      - tensorly-torch==0.5.0
      - torch-harmonics==0.6.3
      - wandb==0.17.4
      - xarray-selafin==0.1.6
prefix: D:\Users\Jonny\miniconda3\envs\ML
