name: ML
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20230802.0
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - attrs=23.1.0
  - black=24.4.2
  - blas=1.0
  - blinker=1.6.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.6.2
  - cachetools=5.3.3
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.0
  - cryptography=42.0.5
  - cycler=0.11.0
  - expat=2.6.2
  - filelock=3.13.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.3.1
  - google-auth=2.29.0
  - google-auth-oauthlib=0.4.1
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gtest=1.14.0
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - isort=5.9.3
  - jinja2=3.1.4
  - joblib=1.4.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=3.20.3
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - multidict=6.0.4
  - mypy_extensions=1.0.0
  - mystmd=1.2.8
  - networkx=3.2.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nodejs=20.12.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - openjpeg=2.4.0
  - openssl=3.3.1
  - packaging=23.2
  - pathspec=0.10.3
  - pillow=10.3.0
  - pip=24.0
  - pip:
    - -r requirements.txt
  - platformdirs=3.10.0
  - plotly=5.9.0
  - ply=3.11
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=5
  - pycparser=2.21
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - pytorch=2.2.0
  - qt-main=5.15.2
  - re2=2022.04.01
  - requests=2.32.2
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - setuptools=69.5.1
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.12
  - tbb=2021.8.0
  - tenacity=8.2.2
  - tensorboard=2.6.0
  - tensorboard-plugin-wit=1.6.0
  - threadpoolctl=2.2.0
  - tk=8.6.14
  - tornado=6.3.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.1
  - vc=14.2
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - werkzeug=3.0.3
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yarl=1.9.3
  - zlib=1.2.13
  - zstd=1.5.5
prefix: D:\Users\Jonathan\scoop\apps\miniconda3\current\envs\ML
